### ISSUE TITLE
Set appliance state- example

### ISSUE THREAD

**Issue by wojciewa** [nbogojevic/midea-beautiful-air#15]
Would it be possible to add a Python example how to set appliance state?

**Comment by deepcoder** [comment]
@nbogojevic It would be very helpful if you would expand your documentation to show setting states. Thank you very much!

**Comment by naro** [comment]
A very rough example I found working. For example Switch on my air conditioner

```
apps = find_appliances(....)
app = apps[0]
app.state.running = True
app.apply()
```
You can find the properties for your appliance in [appliance.py](https://github.com/nbogojevic/midea-beautiful-air/blob/main/midea_beautiful/appliance.py) and you can use properties marked with the `setter` decorator.
