### ISSUE TITLE
Inventor control app

### ISSUE THREAD

**Issue by Jinguba** [nbogojevic/midea-beautiful-air#3]
**Is your feature request related to a problem? Please describe.**
The dehumidifier i bought only alows me to register to app "Inventor control"
as I'm not able to add it in the INVmateII or Midea Air

**Describe the solution you'd like**
Compatibility with this app

**Comment by nbogojevic** [comment]
Hi @Jinguba as far as I know, Inventor control is based on Tuya cloud platform so you could try a client that one. This works only with Midea (msmart) cloud.
