### ISSUE TITLE
[Question] Would this work with a Moovair heat pump?

### ISSUE THREAD

**Issue by Andargor** [nbogojevic/midea-beautiful-air#35]
Sorry if I'm asking a question here, but I didn't see a discussion section. I have a Moovair heat pump with wired controller (rebranded Midea KJR-120N(X6W)/BGEF). My understanding is that Moovair is a Midea rebrand, and if so, your code would work with it?

Do you absolutely need to use the NetHome Plus app with an account or could this be used on the local LAN with no Internet access? I'm asking for security considerations, and also to be able to function if the Internet was not available.

**Comment by VladislavEkimtcov** [comment]
MSmartHome seems to be broken now. Register your appliance in the Midea Air app and it will work, except for 8pm Central for some reason.
