### ISSUE TITLE
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by reneklootwijk** [nbogojevic/midea-beautiful-air#7]
When I run the discovery command like:

```
discover --account xxxx --password xxxx --credentials --proxied
```

I get the following error message:

```
  File "/usr/local/lib/python3.9/site-packages/midea_beautiful_air-0.9.10-py3.9.egg/midea_beautiful/crypto.py", line 536, in sign_proxied
    msg += data
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

It seems to be caused by using the proxied property and not specifying and IOT Key, but I just want to obtain the key and token by logging in using the cloud api. What discovery command should I use for this?

**Comment by nbogojevic** [comment]
It is easier to use `--app` option which is now documented. The proxied and iot should be only for very advanced use - e.g. testing new midea app.
